# 🔗 Comparando, Tratando e Mesclando DataFrames

![Jupyter](https://img.shields.io/badge/Jupyter-111827?style=flat-square&logo=jupyter&logoColor=F37626)
![Python](https://img.shields.io/badge/Python-111827?style=flat-square&logo=python&logoColor=3776AB)
![Pandas](https://img.shields.io/badge/Pandas-150458?style=flat-square&logo=pandas&logoColor=white)
![Python Version](https://img.shields.io/badge/python-3.14+-blue)
![Tópico](https://img.shields.io/badge/tópico-merge%20%7C%20tratamento-teal)
![Dificuldade](https://img.shields.io/badge/dificuldade-Avançado-red)
![Pré-req](https://img.shields.io/badge/pré--req-dataframe%20%7C%20csv-purple)
![Biblioteca](https://img.shields.io/badge/requer-pip%20install%20pandas-orange)

> Vamos trocar os IDs pelos nomes dos produtos, dos clientes e das lojas, para nossas análises ficarem mais intuitivas — usando `merge` para juntar vários DataFrames em um só.


## 📋 Conteúdo

1. [Objetivo](#-1-objetivo)
2. [Criando nossos DataFrames](#️-2-criando-nossos-dataframes)
3. [Tirando as colunas inúteis](#-3-tirando-as-colunas-inúteis)
4. [Juntando os DataFrames com `merge`](#-4-juntando-os-dataframes-com-merge)
5. [Renomeando colunas com `rename`](#️-5-renomeando-colunas-com-rename)
6. [Próximos passos](#-6-próximos-passos)

## 🎯 1. Objetivo

Vamos modificar os IDs para os nomes dos produtos, dos clientes e das lojas, para nossas análises ficarem mais intuitivas futuramente. Para isso, vamos criar um DataFrame com todos os detalhes.

- Usaremos o método `merge` para isso e, depois se quisermos, podemos pegar apenas as colunas que queremos do DataFrame final.

<br>

> ⚠️ **Cuidado:** os arquivos da Contoso usados aqui (`Clientes`, `Lojas`, `Produtos`) têm acentuação e às vezes precisam de um encoding diferente do padrão. Valores para testar: `encoding='latin1'`, `encoding='ISO-8859-1'`, `encoding='utf-8'` ou `encoding='cp1252'`.

---

## ⚙️ 2. Criando nossos DataFrames

- Vamos ler a base de Vendas e as bases de apoio (Clientes, Lojas e Produtos), cada uma com seu próprio encoding

In [10]:
import pandas as pd
from cores import *

vendas_df = pd.read_csv("../spec/Contoso - Vendas - 2017.csv", sep=';')

display(vendas_df[0:21]) # Exibe as primeiras 21 linhas do DataFrame de vendas

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1
10,11,01/01/2017,08/01/2017,7,257,900,5,30488,6,1
11,12,01/01/2017,04/01/2017,3,304,597,10,18561,4,1
12,13,01/01/2017,01/01/2017,0,13,167,2,25632,4,1
13,14,01/01/2017,01/01/2017,0,199,632,2,30401,8,1
14,15,01/01/2017,01/01/2017,0,207,1602,10,36839,8,1
15,16,01/01/2017,06/01/2017,5,309,599,10,27645,16,1
16,17,01/01/2017,01/01/2017,0,225,1383,10,7991,4,1
17,18,01/01/2017,09/01/2017,8,204,882,10,35762,4,1
18,19,01/01/2017,02/01/2017,1,211,1402,10,24240,8,1
19,20,01/01/2017,02/01/2017,1,208,1296,10,13399,8,1
20,21,01/01/2017,05/01/2017,4,207,39,10,27222,8,1

In [11]:
# às vezes precisaremos mudar o encoding — esses arquivos usam acentuação e vieram com encoding diferente do padrão utf-8

clientes_df = pd.read_csv("../spec/Contoso - Clientes.csv", sep=';', encoding='latin1')
lojas_df = pd.read_csv("../spec/Contoso - Lojas.csv", sep=';', encoding='latin1')
produtos_df = pd.read_csv("../spec/Contoso - Produtos Cadastro Completo.csv", sep=';', encoding='latin1')

display(clientes_df[0:21])

,ÿID Cliente,Primeiro Nome,Sobrenome,E-mail,Genero,Numero de Filhos,Data de Nascimento,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Garnet,Lanfranchi,glanfranchi0@mayoclinic.com,Feminino,2,12/05/1995,NaN,NaN,NaN,NaN
1,2,Lurette,Roseblade,lroseblade1@bigcartel.com,Feminino,2,30/06/1943,NaN,NaN,NaN,NaN
2,3,Glenden,Ishchenko,gishchenko2@moonfruit.com,Masculino,5,09/04/1989,NaN,NaN,NaN,NaN
3,4,Baron,Jedrzejewsky,bjedrzejewsky3@e-recht24.de,Masculino,4,17/11/1998,NaN,NaN,NaN,NaN
4,5,Sheree,Bredbury,sbredbury4@sitemeter.com,Feminino,5,08/09/1975,NaN,NaN,NaN,NaN
5,6,Maudie,Hartell,mhartell5@soundcloud.com,Feminino,0,12/03/1988,NaN,NaN,NaN,NaN
6,7,Gayle,Ivimey,givimey6@shinystat.com,Feminino,0,23/06/1993,NaN,NaN,NaN,NaN
7,8,Megan,Tomasian,mtomasian7@google.com.hk,Feminino,0,19/07/1963,NaN,NaN,NaN,NaN
8,9,Cassy,Sherebrook,csherebrook8@chron.com,Feminino,0,26/02/1999,NaN,NaN,NaN,NaN
9,10,Teodor,Rosewall,trosewall9@so-net.ne.jp,Masculino,0,10/07/1997,NaN,NaN,NaN,NaN
10,11,Kelley,Carbonell,kcarbonella@hibu.com,Masculino,0,07/01/2001,NaN,NaN,NaN,NaN
11,12,Leonard,Torn,ltornb@storify.com,Masculino,0,01/07/1967,NaN,NaN,NaN,NaN
12,13,Greta,Halstead,ghalsteadc@twitpic.com,Feminino,3,24/11/1980,NaN,NaN,NaN,NaN
13,14,Michele,Wallett,mwallettd@simplemachines.org,Masculino,0,07/09/1971,NaN,NaN,NaN,NaN
14,15,Greer,Ivoshin,givoshine@ucoz.com,Feminino,0,07/10/1970,NaN,NaN,NaN,NaN
15,16,Torrence,Gommes,tgommesf@illinois.edu,Masculino,0,17/10/2008,NaN,NaN,NaN,NaN
16,17,Trevar,Smolan,tsmolang@sbwire.com,Masculino,1,26/09/1975,NaN,NaN,NaN,NaN
17,18,Siusan,Robins,srobinsh@freewebs.com,Feminino,0,04/03/1967,NaN,NaN,NaN,NaN
18,19,Aubrey,Pennell,apennelli@jalbum.net,Feminino,0,12/03/1989,NaN,NaN,NaN,NaN
19,20,Violetta,Erskin,verskinj@usa.gov,Feminino,0,10/10/2000,NaN,NaN,NaN,NaN
20,21,Peggy,Greeve,pgreevek@w3.org,Feminino,0,09/03/1978,NaN,NaN,NaN,NaN

In [12]:
display(lojas_df[0:21])

,ÿID Loja,Nome da Loja,Quantidade Colaboradores,País
0,1,Loja Contoso Seattle No.1,17.0,Estados Unidos
1,2,Loja Contoso Seattle No.2,25.0,Estados Unidos
2,3,Loja Contoso Kennewick,26.0,Estados Unidos
3,4,Loja Contoso Bellevue,19.0,Estados Unidos
4,5,Loja Contoso Redmond,33.0,Estados Unidos
5,6,Loja Contoso Yakima,47.0,Estados Unidos
6,7,Loja Contoso Granger,22.0,Estados Unidos
7,8,Loja Contoso Sunnyside,17.0,Estados Unidos
8,9,Loja Contoso Toppenish,25.0,Estados Unidos
9,10,Loja Contoso Wapato,25.0,Estados Unidos
10,11,Loja Contoso Cle Elum,26.0,Estados Unidos
11,13,Loja Contoso Snoqualmie,33.0,Estados Unidos
12,14,Loja Contoso Fall City,47.0,Estados Unidos
13,15,Loja Contoso Renton,22.0,Estados Unidos
14,16,Loja Contoso Everett,17.0,Estados Unidos
15,17,Loja Contoso Spokane,25.0,Estados Unidos
16,18,Loja Contoso Veradale,26.0,Estados Unidos
17,20,Loja Contoso Englewood,33.0,Estados Unidos
18,21,Loja Contoso Wheat Ridge,47.0,Estados Unidos
19,22,Loja Contoso Westminster,22.0,Canadá
20,23,Loja Contoso Grand Junction,17.0,Estados Unidos

In [13]:
display(produtos_df[0:21])

,ÿNome do Produto,Descricao do Produto,Fabricante,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,ID Subcategoria
0,Contoso Wireless Laser Mouse E50 Grey,Advanced 2.4 GHz cordless technology makes fre...,"Contoso, Ltd",Contoso,Econômico,"10,69","20,96",873,22
1,Contoso Optical Wheel OEM PS/2 Mouse E60 Grey,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,879,22
2,Contoso Optical Wheel OEM PS/2 Mouse E60 Black,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,880,22
3,Contoso Optical Wheel OEM PS/2 Mouse E60 White,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,881,22
4,Contoso Optical Wheel OEM PS/2 Mouse E60 Silver,"PS/2 mouse, 6 feet mouse cable","Contoso, Ltd",Contoso,Econômico,"6,63",13,882,22
5,Contoso Bluetooth Notebook Mouse E70 Black,Transceiver-free wireless connection to your P...,"Contoso, Ltd",Contoso,Econômico,"25,49",50,887,22
6,Contoso Bluetooth Notebook Mouse E70 White,Transceiver-free wireless connection to your P...,"Contoso, Ltd",Contoso,Econômico,"25,49",50,888,22
7,Contoso Bluetooth Notebook Mouse E70 Silver,Transceiver-free wireless connection to your P...,"Contoso, Ltd",Contoso,Econômico,"25,49",50,889,22
8,Contoso Bluetooth Notebook Mouse E70 Grey,Transceiver-free wireless connection to your P...,"Contoso, Ltd",Contoso,Econômico,"25,49",50,890,22
9,Contoso ADSL Modem Splitter/Filter X 1 E100 Grey,ADSL modem splitter/filter X 1,"Contoso, Ltd",Contoso,Econômico,"9,13","17,9",833,22
10,Contoso ADSL Modem Splitter/Filter X 2 E200 Grey,ADSL modem splitter/filter X 2,"Contoso, Ltd",Contoso,Econômico,"11,68","22,9",834,22
11,Contoso ADSL Modem Splitter/Filter X 3 E300 Grey,ADSL modem splitter/filter X 3,"Contoso, Ltd",Contoso,Econômico,"26,97","52,9",835,22
12,Contoso USB Wave Multi-Media Keyboard E280 Grey,USB wave multimedia keyboard,"Contoso, Ltd",Contoso,Econômico,"8,11","15,9",836,22
13,Contoso Cables To Go USB 2.0 Hard Drive Enclos...,Cables to go USB 2.0 hard drive enclosure,"Contoso, Ltd",Contoso,Econômico,"6,07","11,9",837,22
14,Contoso USB Optical Mouse E200 Gold,USB optical mouse,"Contoso, Ltd",Contoso,Econômico,"7,9","15,5",838,22
15,Contoso Reserve Pen - Tablet Pen E200 Gold,Reserve Pen - Tablet Pen,"Contoso, Ltd",Contoso,Econômico,"7,09","13,9",841,22
16,Contoso Bright Light battery E20 Black,"Illuminate wireless reading device, two super ...","Contoso, Ltd",Contoso,Econômico,"13,71","26,9",842,22
17,Contoso Bright Light battery E20 blue,"Illuminate wireless reading device, two super ...","Contoso, Ltd",Contoso,Econômico,"13,71","26,9",843,22
18,Contoso Bright Light battery E20 Pink,"Illuminate wireless reading device, two super ...","Contoso, Ltd",Contoso,Econômico,"13,71","26,9",844,22
19,Contoso Lens cap E80 White,Lens cap black,"Contoso, Ltd",Contoso,Econômico,"15,27","29,95",800,22
20,Contoso Battery charger - bike E200 White,Primary extended capacity battery pack,"Contoso, Ltd",Contoso,Econômico,"10,15","19,9",801,22

## 🧹 3. Tirando as coluna e infos inúteis ❌👎

Note que: `ID Cliente`, `ID Loja` e `Nome do Produto` vieram com um caractere estranho grudado no nome (efeito do encoding) — e o `clientes_df` ainda trouxe colunas vazias (`Unnamed: ...`). Vamos limpar cada DataFrame, renomeando a coluna de ID e mantendo só o que interessa para o merge.

| Sintaxe 🔑 | O que faz 🔓 |
|---------|-----------|
| `dataframe.drop(columns=['coluna1', 'coluna2'])` | Retira as colunas `coluna1` e `coluna2` |
| `dataframe[['coluna1', 'coluna2']]` | Mantém só as colunas informadas, descartando o resto |
| `dataframe.rename(columns={'nome_velho': 'nome_novo'})` | Renomeia colunas — útil quando o nome veio "sujo" |

<br>

> 💡 **Dica:** `dataframe[['col1', 'col2']]` costuma ser mais direto que `.drop()` quando você quer manter só 2 ou 3 colunas de uma tabela grande.

In [14]:
clientes_df = clientes_df.rename(columns={'ÿID Cliente': 'ID Cliente'})
clientes_df = clientes_df.drop(columns=['Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'])

lojas_df = lojas_df.rename(columns={'ÿID Loja': 'ID Loja'})
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

produtos_df = produtos_df.rename(columns={'ÿNome do Produto': 'Nome do Produto'})
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]

display(clientes_df[0:21])

,ID Cliente,Primeiro Nome,Sobrenome,E-mail,Genero,Numero de Filhos,Data de Nascimento
0,1,Garnet,Lanfranchi,glanfranchi0@mayoclinic.com,Feminino,2,12/05/1995
1,2,Lurette,Roseblade,lroseblade1@bigcartel.com,Feminino,2,30/06/1943
2,3,Glenden,Ishchenko,gishchenko2@moonfruit.com,Masculino,5,09/04/1989
3,4,Baron,Jedrzejewsky,bjedrzejewsky3@e-recht24.de,Masculino,4,17/11/1998
4,5,Sheree,Bredbury,sbredbury4@sitemeter.com,Feminino,5,08/09/1975
5,6,Maudie,Hartell,mhartell5@soundcloud.com,Feminino,0,12/03/1988
6,7,Gayle,Ivimey,givimey6@shinystat.com,Feminino,0,23/06/1993
7,8,Megan,Tomasian,mtomasian7@google.com.hk,Feminino,0,19/07/1963
8,9,Cassy,Sherebrook,csherebrook8@chron.com,Feminino,0,26/02/1999
9,10,Teodor,Rosewall,trosewall9@so-net.ne.jp,Masculino,0,10/07/1997
10,11,Kelley,Carbonell,kcarbonella@hibu.com,Masculino,0,07/01/2001
11,12,Leonard,Torn,ltornb@storify.com,Masculino,0,01/07/1967
12,13,Greta,Halstead,ghalsteadc@twitpic.com,Feminino,3,24/11/1980
13,14,Michele,Wallett,mwallettd@simplemachines.org,Masculino,0,07/09/1971
14,15,Greer,Ivoshin,givoshine@ucoz.com,Feminino,0,07/10/1970
15,16,Torrence,Gommes,tgommesf@illinois.edu,Masculino,0,17/10/2008
16,17,Trevar,Smolan,tsmolang@sbwire.com,Masculino,1,26/09/1975
17,18,Siusan,Robins,srobinsh@freewebs.com,Feminino,0,04/03/1967
18,19,Aubrey,Pennell,apennelli@jalbum.net,Feminino,0,12/03/1989
19,20,Violetta,Erskin,verskinj@usa.gov,Feminino,0,10/10/2000
20,21,Peggy,Greeve,pgreevek@w3.org,Feminino,0,09/03/1978

In [15]:
display(lojas_df[0:21])

    ID Loja                  Nome da Loja
0         1    Loja Contoso Seattle No.1
1         2    Loja Contoso Seattle No.2
2         3       Loja Contoso Kennewick
3         4        Loja Contoso Bellevue
4         5         Loja Contoso Redmond
5         6          Loja Contoso Yakima
6         7         Loja Contoso Granger
7         8       Loja Contoso Sunnyside
8         9       Loja Contoso Toppenish
9        10          Loja Contoso Wapato
10       11        Loja Contoso Cle Elum
11       13      Loja Contoso Snoqualmie
12       14       Loja Contoso Fall City
13       15          Loja Contoso Renton
14       16         Loja Contoso Everett
15       17         Loja Contoso Spokane
16       18        Loja Contoso Veradale
17       20       Loja Contoso Englewood
18       21     Loja Contoso Wheat Ridge
19       22     Loja Contoso Westminster
20       23  Loja Contoso Grand Junction

In [16]:
display(produtos_df[0:21])

    ID Produto                                    Nome do Produto
0          873              Contoso Wireless Laser Mouse E50 Grey
1          879      Contoso Optical Wheel OEM PS/2 Mouse E60 Grey
2          880     Contoso Optical Wheel OEM PS/2 Mouse E60 Black
3          881     Contoso Optical Wheel OEM PS/2 Mouse E60 White
4          882    Contoso Optical Wheel OEM PS/2 Mouse E60 Silver
5          887         Contoso Bluetooth Notebook Mouse E70 Black
6          888         Contoso Bluetooth Notebook Mouse E70 White
7          889        Contoso Bluetooth Notebook Mouse E70 Silver
8          890          Contoso Bluetooth Notebook Mouse E70 Grey
9          833   Contoso ADSL Modem Splitter/Filter X 1 E100 Grey
10         834   Contoso ADSL Modem Splitter/Filter X 2 E200 Grey
11         835   Contoso ADSL Modem Splitter/Filter X 3 E300 Grey
12         836    Contoso USB Wave Multi-Media Keyboard E280 Grey
13         837  Contoso Cables To Go USB 2.0 Hard Drive Enclos...
14         838                Contoso USB Optical Mouse E200 Gold
15         841         Contoso Reserve Pen - Tablet Pen E200 Gold
16         842             Contoso Bright Light battery E20 Black
17         843              Contoso Bright Light battery E20 blue
18         844              Contoso Bright Light battery E20 Pink
19         800                         Contoso Lens cap E80 White
20         801          Contoso Battery charger - bike E200 White

## 🔗 4. Juntando os DataFrames com o método: "`merge`"

Agora vamos juntar os DataFrames para ter 1 único DataFrame com tudo "bonito":

```python
novo_dataframe = dataframe1.merge(dataframe2, on='coluna')
```

| Parte 🔑 | Significado 🔓 |
|-------|-------------|
| `dataframe1.merge(dataframe2, ...)` | Junta as colunas de `dataframe2` ao `dataframe1` |
| `on='coluna'` | A coluna em comum usada para casar as linhas dos dois DataFrames |

> ⚠️ **Cuidado:** o `merge` precisa das colunas com o **mesmo nome** para funcionar. Se não tiver, você precisa alterar o nome da coluna com o `.rename`:
>
> ```python
> dataframe.rename(columns={'coluna1': 'novo_coluna_1'})
> ```

In [ ]:
# juntando os dataframes

vendas_completo_df = vendas_df.merge(clientes_df, on='ID Cliente').merge(produtos_df, on='ID Produto').merge(lojas_df, on='ID Loja')

# exibindo o dataframe final

display(vendas_completo_df[0:21])

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Primeiro Nome,Sobrenome,E-mail,Genero,Numero de Filhos,Data de Nascimento,Nome do Produto,Nome da Loja
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,Rurik,Brumfield,rbrumfieldmy@ameblo.jp,Masculino,4,02/01/1979,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1,Cornelle,Shaw,cshawd4@technorati.com,Feminino,5,09/02/1961,SV DVD 55DVD Storage Binder M56 Black,Loja Contoso North America Reseller
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1,Kermit,Gorrie,kgorriekd@bandcamp.com,Masculino,2,30/12/1958,"The Phone Company Touch Screen Phones 26-2.2"" ...",Loja Contoso Tehran No.2
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1,Angela,Sánchez,angela49@adventure-works.com,Feminino,3,26/08/2012,Contoso Touch Screen Phones - CRT M11 Black,Loja Contoso Singapore
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1,Jacob,Brown,jacob4@adventure-works.com,Masculino,1,02/01/1963,Contoso SLR Camera M146 Orange,Loja Contoso Grand Prairie
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1,Sarah,Woollett,swoollettpb@tuttocitta.it,Feminino,0,12/11/1991,A. Datum SLR Camera M135 Black,Loja Contoso Somerville
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1,Thane,Lefeuvre,tlefeuvrek1@si.edu,Masculino,5,01/11/2001,Contoso Multi-Use Terminal Cable E308 White,Loja Contoso Wapato
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1,Alexia,Washington,alexia11@adventure-works.com,Feminino,4,22/04/1977,A. Datum Compact Digital Camera M200 Grey,Loja Contoso Lisbon
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1,Shannon,Romero,shannon30@adventure-works.com,Feminino,0,18/02/1995,The Phone Company Smart phones Unlocked Intern...,Loja Contoso Knotty Ash
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1,Angel,Allen,angel39@adventure-works.com,Feminino,0,01/02/1993,Contoso 3 Handset Cordless Phone System E30 B...,Loja Contoso North America Online
10,11,01/01/2017,08/01/2017,7,257,900,5,30488,6,1,Arturo,Deng,arturo25@adventure-works.com,Masculino,0,19/07/2003,SV Keyboard E10 White,Loja Contoso Kolkata
11,12,01/01/2017,04/01/2017,3,304,597,10,18561,4,1,Glenn,Atwool,gatwoolfo@bandcamp.com,Feminino,1,23/07/1994,Contoso Screen 85in E085 White,Loja Contoso Saint Petersburg
12,13,01/01/2017,01/01/2017,0,13,167,2,25632,4,1,Kaitlyn,Allen,kaitlyn22@adventure-works.com,Feminino,2,12/08/1961,SV 8xDVD E100 Black,Loja Contoso Snoqualmie
13,14,01/01/2017,01/01/2017,0,199,632,2,30401,8,1,Tiffany,Yang,tiffany5@adventure-works.com,Feminino,0,22/09/1969,WWI Screen 85in E1010 White,Loja Contoso North America Online
14,15,01/01/2017,01/01/2017,0,207,1602,10,36839,8,1,Raymond,Suri,raymond2@adventure-works.com,Masculino,1,26/05/1971,SV DVD 12-Inch Player Portable M400 Black,Loja Contoso Lancashire
15,16,01/01/2017,06/01/2017,5,309,599,10,27645,16,1,Chelsea,Mehta,chelsea15@adventure-works.com,Feminino,3,07/05/1958,Contoso Projector 1080p X980 Silver,Loja Contoso Europe Reseller
16,17,01/01/2017,01/01/2017,0,225,1383,10,7991,4,1,Trudi,Stapforth,tstapforthrk@yale.edu,Feminino,0,06/09/2001,Contoso Dual Handset Cordless Phone System E20...,Loja Contoso Torino
17,18,01/01/2017,09/01/2017,8,204,882,10,35762,4,1,Omar,Xu,omar11@adventure-works.com,Masculino,4,11/09/1971,Contoso Optical Wheel OEM PS/2 Mouse E60 Silver,Loja Contoso York
18,19,01/01/2017,02/01/2017,1,211,1402,10,24240,8,1,Diana,Ortega,diana21@adventure-works.com,Feminino,0,19/12/1978,Contoso Expandable 4-Handset Cordless Phone Sy...,Loja Contoso Stockport
19,20,01/01/2017,02/01/2017,1,208,1296,10,13399,8,1,Ferdinand,Hiley,fhileyb4@springer.com,Masculino,3,26/01/1968,Contoso USB Cable M250 Black,Loja Contoso West Yorkshire
20,21,01/01/2017,05/01/2017,4,207,39,10,27222,8,1,Lacey,Zhu,lacey26@adventure-works.com,Feminino,0,30/03/2001,Contoso 8GB Clock & Radio MP3 Player X850 Green,Loja Contoso Lancashire

## ✏️ 5. Renomeando colunas com `rename`

Vamos renomear o `E-mail` para ficar claro que é do cliente — assim, se mais colunas de e-mail forem adicionadas no futuro (fornecedor, vendedor...), não haverá confusão sobre a quem cada uma pertence.

In [18]:
# vamos renomear o e-mail para ficar claro que é do cliente
vendas_completo_df = vendas_completo_df.rename(columns={'E-mail': 'E-mail Cliente'})

display(vendas_completo_df[0:21])

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Primeiro Nome,Sobrenome,E-mail Cliente,Genero,Numero de Filhos,Data de Nascimento,Nome do Produto,Nome da Loja
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,Rurik,Brumfield,rbrumfieldmy@ameblo.jp,Masculino,4,02/01/1979,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1,Cornelle,Shaw,cshawd4@technorati.com,Feminino,5,09/02/1961,SV DVD 55DVD Storage Binder M56 Black,Loja Contoso North America Reseller
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1,Kermit,Gorrie,kgorriekd@bandcamp.com,Masculino,2,30/12/1958,"The Phone Company Touch Screen Phones 26-2.2"" ...",Loja Contoso Tehran No.2
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1,Angela,Sánchez,angela49@adventure-works.com,Feminino,3,26/08/2012,Contoso Touch Screen Phones - CRT M11 Black,Loja Contoso Singapore
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1,Jacob,Brown,jacob4@adventure-works.com,Masculino,1,02/01/1963,Contoso SLR Camera M146 Orange,Loja Contoso Grand Prairie
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1,Sarah,Woollett,swoollettpb@tuttocitta.it,Feminino,0,12/11/1991,A. Datum SLR Camera M135 Black,Loja Contoso Somerville
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1,Thane,Lefeuvre,tlefeuvrek1@si.edu,Masculino,5,01/11/2001,Contoso Multi-Use Terminal Cable E308 White,Loja Contoso Wapato
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1,Alexia,Washington,alexia11@adventure-works.com,Feminino,4,22/04/1977,A. Datum Compact Digital Camera M200 Grey,Loja Contoso Lisbon
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1,Shannon,Romero,shannon30@adventure-works.com,Feminino,0,18/02/1995,The Phone Company Smart phones Unlocked Intern...,Loja Contoso Knotty Ash
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1,Angel,Allen,angel39@adventure-works.com,Feminino,0,01/02/1993,Contoso 3 Handset Cordless Phone System E30 B...,Loja Contoso North America Online
10,11,01/01/2017,08/01/2017,7,257,900,5,30488,6,1,Arturo,Deng,arturo25@adventure-works.com,Masculino,0,19/07/2003,SV Keyboard E10 White,Loja Contoso Kolkata
11,12,01/01/2017,04/01/2017,3,304,597,10,18561,4,1,Glenn,Atwool,gatwoolfo@bandcamp.com,Feminino,1,23/07/1994,Contoso Screen 85in E085 White,Loja Contoso Saint Petersburg
12,13,01/01/2017,01/01/2017,0,13,167,2,25632,4,1,Kaitlyn,Allen,kaitlyn22@adventure-works.com,Feminino,2,12/08/1961,SV 8xDVD E100 Black,Loja Contoso Snoqualmie
13,14,01/01/2017,01/01/2017,0,199,632,2,30401,8,1,Tiffany,Yang,tiffany5@adventure-works.com,Feminino,0,22/09/1969,WWI Screen 85in E1010 White,Loja Contoso North America Online
14,15,01/01/2017,01/01/2017,0,207,1602,10,36839,8,1,Raymond,Suri,raymond2@adventure-works.com,Masculino,1,26/05/1971,SV DVD 12-Inch Player Portable M400 Black,Loja Contoso Lancashire
15,16,01/01/2017,06/01/2017,5,309,599,10,27645,16,1,Chelsea,Mehta,chelsea15@adventure-works.com,Feminino,3,07/05/1958,Contoso Projector 1080p X980 Silver,Loja Contoso Europe Reseller
16,17,01/01/2017,01/01/2017,0,225,1383,10,7991,4,1,Trudi,Stapforth,tstapforthrk@yale.edu,Feminino,0,06/09/2001,Contoso Dual Handset Cordless Phone System E20...,Loja Contoso Torino
17,18,01/01/2017,09/01/2017,8,204,882,10,35762,4,1,Omar,Xu,omar11@adventure-works.com,Masculino,4,11/09/1971,Contoso Optical Wheel OEM PS/2 Mouse E60 Silver,Loja Contoso York
18,19,01/01/2017,02/01/2017,1,211,1402,10,24240,8,1,Diana,Ortega,diana21@adventure-works.com,Feminino,0,19/12/1978,Contoso Expandable 4-Handset Cordless Phone Sy...,Loja Contoso Stockport
19,20,01/01/2017,02/01/2017,1,208,1296,10,13399,8,1,Ferdinand,Hiley,fhileyb4@springer.com,Masculino,3,26/01/1968,Contoso USB Cable M250 Black,Loja Contoso West Yorkshire
20,21,01/01/2017,05/01/2017,4,207,39,10,27222,8,1,Lacey,Zhu,lacey26@adventure-works.com,Feminino,0,30/03/2001,Contoso 8GB Clock & Radio MP3 Player X850 Green,Loja Contoso Lancashire

### Agora podemos começar as análises