# 🔍 Filtrando Informações nos DataFrames

![Jupyter](https://img.shields.io/badge/Jupyter-111827?style=flat-square&logo=jupyter&logoColor=F37626)
![Python](https://img.shields.io/badge/Python-111827?style=flat-square&logo=python&logoColor=3776AB)
![Pandas](https://img.shields.io/badge/Pandas-150458?style=flat-square&logo=pandas&logoColor=white)
![Python Version](https://img.shields.io/badge/python-3.14+-blue)
![Tópico](https://img.shields.io/badge/tópico-filtragem%20%7C%20condições-teal)
![Dificuldade](https://img.shields.io/badge/dificuldade-Avançado-red)
![Pré-req](https://img.shields.io/badge/pré--req-dataframe%20%7C%20merge-purple)
![Biblioteca](https://img.shields.io/badge/requer-pip%20install%20pandas-orange)

> Um dos grandes potenciais do pandas é tratar condições. A forma com que analisamos condições em um DataFrame é diferente do que já fizemos até agora no curso — vamos ver como funciona.


## 📋 Conteúdo

1. [Preparando as bases de dados](#️-1-preparando-as-bases-de-dados)
2. [Qual o % das vendas que foi devolvido?](#-2-qual-o--das-vendas-que-foi-devolvido)
3. [Filtrando por uma loja específica](#-3-filtrando-por-uma-loja-específica)
4. [Entendendo o filtro em 2 passos](#-4-entendendo-o-filtro-em-2-passos)
5. [Desafio: filtrando com 2 condições](#-5-desafio-filtrando-com-2-condições)

---

## ⚙️ 1. Preparando as bases de dados

- Preparando as bases de dados (o que fizemos nas últimas aulas)

In [7]:
import pandas as pd

# importando os arquivos
vendas_df = pd.read_csv(r'../spec/Contoso - Vendas - 2017.csv', sep=';', encoding='latin1')
produtos_df = pd.read_csv(r'../spec/Contoso - Produtos Cadastro Completo.csv', sep=';', encoding='latin1')
lojas_df = pd.read_csv(r'../spec/Contoso - Lojas.csv', sep=';', encoding='latin1')
clientes_df = pd.read_csv(r'../spec/Contoso - Clientes.csv', sep=';', encoding='latin1')

# Ajustar nome das colunas
produtos_df.rename(columns={'ÿNome do Produto': 'Nome do Produto'}, inplace=True)
clientes_df.rename(columns={'ÿID Cliente': 'ID Cliente'}, inplace=True)
lojas_df.rename(columns={'ÿID Loja': 'ID Loja'}, inplace=True)

# limpando apenas as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome do Produto']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

# mesclando e renomeando os dataframes
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail': 'E-mail do Cliente'})

#print 
display(vendas_df[0:21])

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum Advanced Digital Camera M300 Pink,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1,SV DVD 55DVD Storage Binder M56 Black,Loja Contoso North America Reseller,cshawd4@technorati.com
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1,"The Phone Company Touch Screen Phones 26-2.2"" ...",Loja Contoso Tehran No.2,kgorriekd@bandcamp.com
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1,Contoso Touch Screen Phones - CRT M11 Black,Loja Contoso Singapore,angela49@adventure-works.com
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1,Contoso SLR Camera M146 Orange,Loja Contoso Grand Prairie,jacob4@adventure-works.com
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1,A. Datum SLR Camera M135 Black,Loja Contoso Somerville,swoollettpb@tuttocitta.it
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1,Contoso Multi-Use Terminal Cable E308 White,Loja Contoso Wapato,tlefeuvrek1@si.edu
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1,A. Datum Compact Digital Camera M200 Grey,Loja Contoso Lisbon,alexia11@adventure-works.com
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1,The Phone Company Smart phones Unlocked Intern...,Loja Contoso Knotty Ash,shannon30@adventure-works.com
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1,Contoso 3 Handset Cordless Phone System E30 B...,Loja Contoso North America Online,angel39@adventure-works.com
10,11,01/01/2017,08/01/2017,7,257,900,5,30488,6,1,SV Keyboard E10 White,Loja Contoso Kolkata,arturo25@adventure-works.com
11,12,01/01/2017,04/01/2017,3,304,597,10,18561,4,1,Contoso Screen 85in E085 White,Loja Contoso Saint Petersburg,gatwoolfo@bandcamp.com
12,13,01/01/2017,01/01/2017,0,13,167,2,25632,4,1,SV 8xDVD E100 Black,Loja Contoso Snoqualmie,kaitlyn22@adventure-works.com
13,14,01/01/2017,01/01/2017,0,199,632,2,30401,8,1,WWI Screen 85in E1010 White,Loja Contoso North America Online,tiffany5@adventure-works.com
14,15,01/01/2017,01/01/2017,0,207,1602,10,36839,8,1,SV DVD 12-Inch Player Portable M400 Black,Loja Contoso Lancashire,raymond2@adventure-works.com
15,16,01/01/2017,06/01/2017,5,309,599,10,27645,16,1,Contoso Projector 1080p X980 Silver,Loja Contoso Europe Reseller,chelsea15@adventure-works.com
16,17,01/01/2017,01/01/2017,0,225,1383,10,7991,4,1,Contoso Dual Handset Cordless Phone System E20...,Loja Contoso Torino,tstapforthrk@yale.edu
17,18,01/01/2017,09/01/2017,8,204,882,10,35762,4,1,Contoso Optical Wheel OEM PS/2 Mouse E60 Silver,Loja Contoso York,omar11@adventure-works.com
18,19,01/01/2017,02/01/2017,1,211,1402,10,24240,8,1,Contoso Expandable 4-Handset Cordless Phone Sy...,Loja Contoso Stockport,diana21@adventure-works.com
19,20,01/01/2017,02/01/2017,1,208,1296,10,13399,8,1,Contoso USB Cable M250 Black,Loja Contoso West Yorkshire,fhileyb4@springer.com
20,21,01/01/2017,05/01/2017,4,207,39,10,27222,8,1,Contoso 8GB Clock & Radio MP3 Player X850 Green,Loja Contoso Lancashire,lacey26@adventure-works.com

## 📊 2. Qual o % das vendas que foi devolvido?

Primeiro vamos aplicar uma função normalmente, sem nenhum filtro. Para isso vamos somar as quantidades nas colunas correspondentes. Lembrando, o % vai ser: `Total Devolvido / Total Vendido`.

| Método | O que faz |
|--------|-----------|
| `dataframe['coluna'].sum()` | Soma todos os valores da coluna |

In [2]:
qtde_vendida = vendas_df['Quantidade Vendida'].sum()
qtde_devolvida = vendas_df['Quantidade Devolvida'].sum()

perc_devolucao = qtde_devolvida / qtde_vendida
print(f'{perc_devolucao:.2%}')

1.17%

## 🏬 3. Filtrando por uma loja específica

Agora, se quisermos fazer a mesma análise apenas para 1 loja: queremos filtrar apenas os itens da Loja Contoso Europe Online e saber o % de devolução dessa loja.

Para isso, vamos precisar filtrar. A forma de filtrar um DataFrame é uma "simples" comparação:

```python
dataframe[dataframe['coluna'] == valor]
```

| Parte | Significado |
|-------|-------------|
| `dataframe['coluna'] == valor` | Cria uma condição: compara cada linha da coluna com o valor e retorna `True`/`False` |
| `dataframe[condição]` | Mantém apenas as linhas onde a condição é `True` |

> ⚠️ **Cuidado:** os nomes das lojas nessa base vêm com um espaço extra no final (ex.: `'Loja Contoso Europe Online '`), efeito da própria origem dos dados. Preste atenção na comparação exata.

In [ ]:
vendas_europe_df = vendas_df[vendas_df['Nome da Loja'] == 'Loja Contoso Europe Online ']

qtde_vendida_europe = vendas_europe_df['Quantidade Vendida'].sum()
qtde_devolvida_europe = vendas_europe_df['Quantidade Devolvida'].sum()

perc_devolucao_europe = (qtde_devolvida_europe / qtde_vendida_europe)

print(f'{perc_devolucao_europe:.2%}')

1.33%

## 🪜 4. Entendendo o filtro em 2 passos

Vamos fazer em 2 passos para entender certinho o que está acontecendo por trás da comparação.

1. **Passo 1:** `vendas_df['Nome da Loja'] == 'Loja Contoso Europe Online '` sozinho já retorna uma coisa — uma `Series` de `True`/`False`, uma para cada linha do DataFrame (essa é a **condição**, ou **máscara booleana**).
2. **Passo 2:** usamos essa máscara dentro de `vendas_df[...]` para manter só as linhas marcadas como `True`.

In [9]:
# Passo 1: criando a condição (máscara booleana)
condicao_europe = vendas_df['Nome da Loja'] == "Loja Contoso Europe Online"

display(condicao_europe[0:21])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
Name: Nome da Loja, dtype: bool

In [11]:
# Passo 2: usando a condição para filtrar o dataframe
vendas_europe_df = vendas_df[condicao_europe]

display(vendas_europe_df[0:21])

Empty DataFrame
Columns: [Numero da Venda, Data da Venda, Data do Envio, ID Canal, ID Loja, ID Produto, ID Promocao, ID Cliente, Quantidade Vendida, Quantidade Devolvida, Nome do Produto, Nome da Loja, E-mail do Cliente]
Index: []

## 🧩 5. Desafio: filtrando com 2 condições

E se eu quisesse criar uma tabela apenas com as vendas da Loja Contoso Europe Online que não tiveram nenhuma devolução? Quero criar essa tabela e saber quantas vendas são.

Repare que nesse caso são 2 condições ao mesmo tempo — como fazemos isso?

| Operador | Significado |
|----------|-------------|
| `&` | **E** — as duas condições precisam ser verdadeiras |
| `\|` | **OU** — pelo menos uma das condições precisa ser verdadeira |

> ⚠️ **Cuidado:** ao combinar condições, cada uma precisa ficar entre parênteses: `dataframe[(condição1) & (condição2)]`. Sem os parênteses o Python não entende a prioridade das operações e dá erro.

In [13]:
# tudo junto
vendas_europe_sem_devolucao_df = vendas_df[(vendas_df['Nome da Loja'] == 'Loja Contoso Europe Online ') & (vendas_df['Quantidade Devolvida'] == 0)]

display(vendas_europe_sem_devolucao_df[0:5]) #top 5

print(f'Total de vendas: {len(vendas_europe_sem_devolucao_df)}')

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
98,99,01/01/2017,03/01/2017,2,306,1269,10,26238,8,0,Contoso Carrying Case E312 Blue,Loja Contoso Europe Online,edward17@adventure-works.com
165,166,01/01/2017,02/01/2017,1,306,1107,10,7242,16,0,"Contoso SLR Camera 35"" M358 Orange",Loja Contoso Europe Online,khanhard6r@taobao.com
166,167,01/01/2017,05/01/2017,4,306,242,10,34277,16,0,Contoso Home Theater System 7.1 Channel M1700 ...,Loja Contoso Europe Online,marshall24@adventure-works.com
186,187,01/01/2017,06/01/2017,5,306,1479,10,23132,8,0,The Phone Company Smart phones Unlocked Intern...,Loja Contoso Europe Online,cynthia4@adventure-works.com
198,199,01/01/2017,03/01/2017,2,306,819,10,5363,4,0,Contoso Laptop Cooling Hub notebook fan with 4...,Loja Contoso Europe Online,svirgoea4@blogtalkradio.com

Total de vendas: 35029

In [7]:
# separado
condicao_loja = vendas_df['Nome da Loja'] == 'Loja Contoso Europe Online '
condicao_sem_devolucao = vendas_df['Quantidade Devolvida'] == 0

vendas_europe_sem_devolucao_df = vendas_df[condicao_loja & condicao_sem_devolucao]

display(vendas_europe_sem_devolucao_df)
print(f'Total de vendas: {len(vendas_europe_sem_devolucao_df)}')

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome do Produto,Nome da Loja,E-mail do Cliente
98,99,01/01/2017,03/01/2017,2,306,1269,10,26238,8,0,Contoso Carrying Case E312 Blue,Loja Contoso Europe Online,edward17@adventure-works.com
165,166,01/01/2017,02/01/2017,1,306,1107,10,7242,16,0,"Contoso SLR Camera 35"" M358 Orange",Loja Contoso Europe Online,khanhard6r@taobao.com
166,167,01/01/2017,05/01/2017,4,306,242,10,34277,16,0,Contoso Home Theater System 7.1 Channel M1700 ...,Loja Contoso Europe Online,marshall24@adventure-works.com
186,187,01/01/2017,06/01/2017,5,306,1479,10,23132,8,0,The Phone Company Smart phones Unlocked Intern...,Loja Contoso Europe Online,cynthia4@adventure-works.com
198,199,01/01/2017,03/01/2017,2,306,819,10,5363,4,0,Contoso Laptop Cooling Hub notebook fan with 4...,Loja Contoso Europe Online,svirgoea4@blogtalkradio.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980579,980580,31/12/2017,06/01/2018,6,306,771,10,6539,8,0,Contoso USB Wave Multi-media Keyboard E280 Black,Loja Contoso Europe Online,hgauntleyf0@smh.com.au
980580,980581,31/12/2017,01/01/2018,1,306,591,10,32061,8,0,Contoso Projector 480p M480 White,Loja Contoso Europe Online,gina18@adventure-works.com
980581,980582,31/12/2017,31/12/2017,0,306,1388,10,22838,8,0,Contoso Private Branch Exchange M88 Grey,Loja Contoso Europe Online,alexa14@adventure-works.com
980582,980583,31/12/2017,03/01/2018,3,306,1354,10,33450,8,0,Contoso Hybrid system M60 White,Loja Contoso Europe Online,alexis3@adventure-works.com
980632,980633,31/12/2017,31/12/2017,0,306,1086,10,12240,4,0,Contoso SLR Camera M143 Grey,Loja Contoso Europe Online,gtabert6p@friendfeed.com

Total de vendas: 35029