# 🧮 Exercício - Mini Projeto de Análise de Dados

![Jupyter](https://img.shields.io/badge/Jupyter-111827?style=flat-square&logo=jupyter&logoColor=F37626)
![Python](https://img.shields.io/badge/Python-111827?style=flat-square&logo=python&logoColor=3776AB)
![Pandas](https://img.shields.io/badge/Pandas-150458?style=flat-square&logo=pandas&logoColor=white)
![Openpyxl](https://img.shields.io/badge/Openpyxl-217346?style=flat-square&logo=microsoft-excel&logoColor=white)
![Python Version](https://img.shields.io/badge/python-3.14+-blue)
![Tópico](https://img.shields.io/badge/tópico-exercício%20%7C%20pandas%20%7C%20análise-teal)
![Dificuldade](https://img.shields.io/badge/dificuldade-Avançado-red)
![Pré-req](https://img.shields.io/badge/pré--req-merge%20%7C%20groupby%20%7C%20read__csv%20%7C%20read__excel-purple)
![Biblioteca](https://img.shields.io/badge/requer-pip%20install%20pandas%20&&_openpyxl-orange)

> Fechando o módulo de pandas com um miniprojeto completo: 3 bases diferentes (2 csv + 1 excel), encodings distintos, `merge`, `groupby` e `unique()` — praticamente um resumo de tudo que vimos até aqui.

## 📋 Conteúdo

1. [Contexto e Enunciado](#-1-contexto-e-enunciado)
2. [Importando as Bases](#-2-importando-as-bases)
3. [Valor Total da Folha Salarial](#-3-valor-total-da-folha-salarial)
4. [Faturamento da Empresa](#-4-faturamento-da-empresa)
5. [Percentual de Funcionários com Contrato Fechado](#-5-percentual-de-funcionários-com-contrato-fechado)
6. [Contratos Fechados por Área](#-6-contratos-fechados-por-área)
7. [Funcionários por Área](#-7-funcionários-por-área)
8. [Ticket Médio Mensal dos Contratos](#-8-ticket-médio-mensal-dos-contratos)
9. [Resumo Final](#-9-resumo-final)

## 📄 1. Contexto e Enunciado

Vamos fazer um exercício completo de pandas para um miniprojeto de análise de dados.

Esse exercício vai obrigar a gente a usar boa parte dos conhecimento de pandas e até de outros módulos que já aprendemos ao longo do curso.

### 📦 O que temos?

Temos os dados de 2019 de uma empresa de prestação de serviços.

- CadastroFuncionarios
- CadastroClientes
- BaseServiçosPrestados

Obs1: Para ler arquivos csv, temos o read_csv<br>
Obs2: Para ler arquivos xlsx (arquivos em excel normais, que não são padrão csv), temos o read_excel

### 🎯 O que queremos saber/fazer?

1. Valor Total da Folha Salarial -> Qual foi o gasto total com salários de funcionários pela empresa? <br>
    Sugestão: calcule o salário total de cada funcionário, salário + benefícios + impostos, depois some todos os salários


2. Qual foi o faturamento da empresa?<br>
    Sugestão: calcule o faturamento total de cada serviço e depois some o faturamento de todos


3. Qual o % de funcionários que já fechou algum contrato?<br>
    Sugestão: na base de serviços temos o funcionário que fechou cada serviço. Mas nem todos os funcionários que a empresa tem já fecharam algum serviço.<br>
    . Na base de funcionários temos uma lista com todos os funcionários<br>
    . Queremos calcular Qtde_Funcionarios_Fecharam_Serviço / Qtde_Funcionários_Totais<br>
    . Para calcular a qtde de funcionários que fecharam algum serviço, use a base de serviços e conte quantos funcionários tem ali. Mas lembre-se, cada funcionário só pode ser contado uma única vez.<br><br>
    Dica: se você aplicar o método .unique() em uma variável que é apenas 1 coluna de um dataframe, ele vai excluir todos os valores duplicados daquela coluna.<br>
    Ex: unicos_colunaA = dataframe['colunaA'].unique() te dá como resposta uma lista com todos os itens da colunaA aparecendo uma única vez. Todos os valores repetidos da colunaA são excluidos da variável unicos_colunaA


4. Calcule o total de contratos que cada área da empresa já fechou


5. Calcule o total de funcionários por área


6. Qual o ticket médio mensal (faturamento médio mensal) dos contratos?<br>
    Dica: .mean() calcula a média -> exemplo: media_colunaA = dataframe['colunaA'].mean()

Obs: Lembrando as opções mais usuais de encoding:<br>
encoding='latin1', encoding='ISO-8859-1', encoding='utf-8' ou então encoding='cp1252'

Observação Importante: Se o seu código der um erro na hora de importar os arquivos:<br>
- CadastroClientes.csv
- CadastroFuncionarios.csv

Use separador ";" (ponto e vírgula) para resolver

## 📥 2. Importando as Bases

3 arquivos, 3 jeitos de ler:

| Arquivo | Formato | Parâmetros usados | Motivo |
|---|---|---|---|
| `CadastroFuncionarios.csv` | csv | `sep=';', encoding='utf-8', decimal=','` | separador `;` e valores decimais com vírgula (ex: `574,04`) |
| `CadastroClientes.csv` | csv | `sep=';', encoding='utf-8'` | separador `;` |
| `BaseServiçosPrestados.xlsx` | xlsx | `read_excel` (padrão) | arquivo Excel, sem separador/encoding |

<br>

> 💡 **Dica:** o parâmetro `decimal=','` avisa o pandas que a vírgula é o separador decimal (padrão brasileiro) — sem ele, colunas como `Impostos` e `Beneficios` (que têm valores como `574,04`) viram texto (`object`) em vez de número.

In [1]:
import pandas as pd
from cores import *

# importando as 3 bases do exercício

funcionarios_df = pd.read_csv(r'../spec/CadastroFuncionarios.csv', sep=';', encoding='utf-8', decimal=',')
clientes_df = pd.read_csv(r'../spec/CadastroClientes.csv', sep=';', encoding='utf-8')
servicos_df = pd.read_excel(r'../spec/BaseServiçosPrestados.xlsx')

In [2]:
display(funcionarios_df.head())

,ID Funcionário,Estado Civil,Nome Completo,Salario Base,Impostos,Beneficios,VT,VR,Cargo,Area
0,1,C,Gabriel Mesquita,21910,10955.0,4382.0,242,719.04,Diretor,Operações
1,2,C,João Haddad,5404,2702.0,1080.8,154,574.56,Estagiário,Logística
2,3,C,Amanda Marques Ribeiro,16066,8033.0,3213.2,154,729.12,Estagiário,Administrativo
3,4,C,Guilherme Nunez,21305,10652.5,4261.0,220,524.16,Analista,Administrativo
4,5,C,Adelino Gomes,5098,2549.0,1019.6,176,725.76,Analista,Administrativo

In [3]:
display(clientes_df.head())

   ID Cliente             Cliente  Valor Contrato Mensal
0           1  Teixeira Gonçalves                    540
1           2        Souza Santos                   1260
2           3        Emídio Alves                   3195
3           4        Santos Costa                   2520
4           5         Do Monteiro                   3510

In [4]:
display(servicos_df.head())

,Codigo do Servico,ID Funcionário,ID Cliente,Tempo Total de Contrato (Meses)
0,OS0001,67,1,14
1,OS0002,17,2,12
2,OS0003,116,4,14
3,OS0004,37,5,8
4,OS0005,130,6,8

## 💰 3. Valor Total da Folha Salarial

| Coluna 🔑 | O que é 🔓 |
|---|---|
| `Salario Base` | salário fixo do funcionário |
| `Beneficios` | valor de benefícios (plano de saúde, vale-refeição, etc) |
| `Impostos` | impostos pagos pela empresa sobre o funcionário |

Salário Total de cada funcionário = `Salario Base` + `Beneficios` + `Impostos`. Depois é só somar a coluna inteira.

In [5]:
funcionarios_df['Salario Total'] = funcionarios_df['Salario Base'] + funcionarios_df['Beneficios'] + funcionarios_df['Impostos']

folha_salarial = funcionarios_df['Salario Total'].sum()

print(f"{CinzaClaro}Valor Total da Folha Salarial:{Reset} {VerdeClaro}R${folha_salarial:,.2f}{Reset}")

Valor Total da Folha Salarial: R$2,614,343.30

## 📈 4. Faturamento da Empresa

A base de serviços não tem o valor do contrato — quem tem é a base de clientes (`Valor Contrato Mensal`). Precisamos juntar as duas.

| Método 🔑 | O que faz 🔓 |
|---|---|
| `.merge(clientes_df, on='ID Cliente')` | traz o valor mensal do contrato de cada cliente para a base de serviços |
| `Valor Contrato Mensal * Tempo Total de Contrato (Meses)` | faturamento total daquele contrato específico |

In [6]:
servicos_clientes_df = servicos_df.merge(clientes_df, on='ID Cliente')

servicos_clientes_df['Faturamento'] = servicos_clientes_df['Valor Contrato Mensal'] * servicos_clientes_df['Tempo Total de Contrato (Meses)']

faturamento_total = servicos_clientes_df['Faturamento'].sum()

print(f"{CinzaClaro}Faturamento Total da Empresa:{Reset} {VerdeClaro}R${faturamento_total:,.2f}{Reset}")

Faturamento Total da Empresa: R$5,519,160.00

## 🤝 5. Percentual de Funcionários com Contrato Fechado

| Método 🔑 | O que faz 🔓 |
|---|---|
| `servicos_df['ID Funcionário'].unique()` | lista dos funcionários que aparecem na base de serviços, sem repetição |
| `len(...)` | quantidade de funcionários únicos |

% = Qtde_Funcionarios_Fecharam_Serviço / Qtde_Funcionários_Totais

In [13]:
funcionarios_com_contrato = servicos_df['ID Funcionário'].unique()

qtde_funcionarios_com_contrato = len(funcionarios_com_contrato)
qtde_funcionarios_total = funcionarios_df.shape[0]

perc_funcionarios_com_contrato = qtde_funcionarios_com_contrato / qtde_funcionarios_total

print(f"{CinzaClaro}Funcionários com contrato fechado:{Reset} {VerdeClaro}{qtde_funcionarios_com_contrato}{Reset} {CinzaClaro}de{Reset} {VerdeClaro}{qtde_funcionarios_total}{Reset}")

print(f"{CinzaClaro}% de Funcionários que já Fecharam Contrato:{Reset} {VerdeClaro}{perc_funcionarios_com_contrato:.2%}{Reset}")

Funcionários com contrato fechado: 99 de 114
% de Funcionários que já Fecharam Contrato: 86.84%

## 🏢 6. Contratos Fechados por Área

Cada linha de `servicos_df` é um contrato. Para saber a área de quem fechou, precisamos trazer a coluna `Area` (que só existe em `funcionarios_df`) via `merge`, e então agrupar.

| Método 🔑 | O que faz 🔓 |
|---|---|
| `.merge(funcionarios_df[['ID Funcionário', 'Area']], on='ID Funcionário')` | traz a área de cada funcionário para a base de serviços |
| `.groupby('Area')['Codigo do Servico'].count()` | conta quantos contratos (linhas) cada área fechou |

In [16]:
servicos_area_df = servicos_df.merge(funcionarios_df[['ID Funcionário', 'Area']], on='ID Funcionário')

contratos_por_area = servicos_area_df.groupby('Area')['Codigo do Servico'].count()

display("Contratos por Área: ", contratos_por_area)

'Contratos por Área:'

Area
Administrativo    63
Comercial         44
Financeiro        42
Logística         40
Operações         48
Name: Codigo do Servico, dtype: int64

## 👥 7. Funcionários por Área

Aqui não precisa de `merge` — a própria base de funcionários já tem a coluna `Area`.

In [9]:
funcionarios_por_area = funcionarios_df.groupby('Area')['ID Funcionário'].count()

display(funcionarios_por_area)

Area
Administrativo    26
Comercial         26
Financeiro        18
Logística         21
Operações         23
Name: ID Funcionário, dtype: int64

## 🎫 8. Ticket Médio Mensal dos Contratos

Usando a base já mesclada em [4. Faturamento da Empresa](#-4-faturamento-da-empresa) (`servicos_clientes_df`, 1 linha por contrato), o ticket médio mensal é a média da coluna `Valor Contrato Mensal`.

In [10]:
ticket_medio_mensal = servicos_clientes_df['Valor Contrato Mensal'].mean()

print(f"{CinzaClaro}Ticket Médio Mensal dos Contratos:{Reset} {VerdeClaro}R${ticket_medio_mensal:,.2f}{Reset}")

Ticket Médio Mensal dos Contratos: R$2,438.35

## ✅ 9. Resumo Final

In [11]:
print(f"{CinzaClaro}1. Folha Salarial Total:{Reset} {VerdeClaro}R${folha_salarial:,.2f}{Reset}")
print(f"{CinzaClaro}2. Faturamento Total:{Reset} {VerdeClaro}R${faturamento_total:,.2f}{Reset}")
print(f"{CinzaClaro}3. % Funcionários com Contrato:{Reset} {VerdeClaro}{perc_funcionarios_com_contrato:.2%}{Reset}")
print(f"{CinzaClaro}4. Contratos por Área:{Reset}\n{contratos_por_area}")
print(f"{CinzaClaro}5. Funcionários por Área:{Reset}\n{funcionarios_por_area}")
print(f"{CinzaClaro}6. Ticket Médio Mensal:{Reset} {VerdeClaro}R${ticket_medio_mensal:,.2f}{Reset}")

1. Folha Salarial Total: R$2,614,343.30
2. Faturamento Total: R$5,519,160.00
3. % Funcionários com Contrato: 86.84%
4. Contratos por Área:
Area
Administrativo    63
Comercial         44
Financeiro        42
Logística         40
Operações         48
Name: Codigo do Servico, dtype: int64
5. Funcionários por Área:
Area
Administrativo    26
Comercial         26
Financeiro        18
Logística         21
Operações         23
Name: ID Funcionário, dtype: int64
6. Ticket Médio Mensal: R$2,438.35